# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/plokamar/Documents/UnrealEngine

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	ObstacleCourse-Android-DebugGame  \
	ObstacleCourse-Android-Development  \
	ObstacleCourse-Android-Shipping  \
	ObstacleCourse-Linux-DebugGame  \
	ObstacleCourse-Linux-Development  \
	ObstacleCourse-Linux-Shipping  \
	ObstacleCourse-LinuxArm64-DebugGame  \
	ObstacleCourse-LinuxArm64-Development  \
	ObstacleCourse-LinuxArm64-Shipping  \
	ObstacleCourse \
	ObstacleCourseEditor-Linux-DebugGame  \
	ObstacleCourseEditor-Linux-Development  \
	ObstacleCourseEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend ObstacleCourseEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug ObstacleCourseEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

ObstacleCourse-Android-DebugGame:
	 $(BUILD) ObstacleCourse Android DebugGame  -Project="/home/plokamar/Documents/UnrealProjects/ObstacleCourse/ObstacleCourse.uproject" $(ARGS)

ObstacleCourse-Android-Development:
	 $(BUILD) ObstacleCourse Android Development  -Project="/home/plokamar/Documents/UnrealProjects/ObstacleCourse/ObstacleCourse.uproject" $(ARGS)

ObstacleCourse-Android-Shipping:
	 $(BUILD) ObstacleCourse Android Shipping  -Project="/home/plokamar/Documents/UnrealProjects/ObstacleCourse/ObstacleCourse.uproject" $(ARGS)

ObstacleCourse-Linux-DebugGame:
	 $(BUILD) ObstacleCourse Linux DebugGame  -Project="/home/plokamar/Documents/UnrealProjects/ObstacleCourse/ObstacleCourse.uproject" $(ARGS)

ObstacleCourse-Linux-Development:
	 $(BUILD) ObstacleCourse Linux Development  -Project="/home/plokamar/Documents/UnrealProjects/ObstacleCourse/ObstacleCourse.uproject" $(ARGS)

ObstacleCourse-Linux-Shipping:
	 $(BUILD) ObstacleCourse Linux Shipping  -Project="/home/plokamar/Documents/UnrealProjects/ObstacleCourse/ObstacleCourse.uproject" $(ARGS)

ObstacleCourse-LinuxArm64-DebugGame:
	 $(BUILD) ObstacleCourse LinuxArm64 DebugGame  -Project="/home/plokamar/Documents/UnrealProjects/ObstacleCourse/ObstacleCourse.uproject" $(ARGS)

ObstacleCourse-LinuxArm64-Development:
	 $(BUILD) ObstacleCourse LinuxArm64 Development  -Project="/home/plokamar/Documents/UnrealProjects/ObstacleCourse/ObstacleCourse.uproject" $(ARGS)

ObstacleCourse-LinuxArm64-Shipping:
	 $(BUILD) ObstacleCourse LinuxArm64 Shipping  -Project="/home/plokamar/Documents/UnrealProjects/ObstacleCourse/ObstacleCourse.uproject" $(ARGS)

ObstacleCourse: ObstacleCourse-Linux-Development

ObstacleCourseEditor-Linux-DebugGame:
	 $(BUILD) ObstacleCourseEditor Linux DebugGame  -Project="/home/plokamar/Documents/UnrealProjects/ObstacleCourse/ObstacleCourse.uproject" $(ARGS)

ObstacleCourseEditor-Linux-Development:
	 $(BUILD) ObstacleCourseEditor Linux Development  -Project="/home/plokamar/Documents/UnrealProjects/ObstacleCourse/ObstacleCourse.uproject" $(ARGS)

ObstacleCourseEditor: ObstacleCourseEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/plokamar/Documents/UnrealProjects/ObstacleCourse/ObstacleCourse.uproject" -Game 

.PHONY: $(TARGETS)
